import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SignInButtonFacebook from "./components/SignInButtonFacebook";
import SignInButtonGitHub from "./components/SignInButtonGitHub";
import SignInButtonGoogle from "./components/SignInButtonGoogle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <p>Header</p>
        </header>
        <main>
          <div className="container mx-auto px-4 py-16 display flex wrap">
            <ul>
            <SignInButtonFacebook/>
            <SignInButtonGitHub/>
            <SignInButtonGoogle/>
            </ul>

          </div>
        </main>
        <footer>
          <p>Footer</p>
        </footer>
        {children}
      </body>
    </html>
  );
}
